/* phxrpc_scheduler_service.cpp

 Generated by phxrpc_pb2service from scheduler.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc/file.h"

#include "phxrpc_scheduler_service.h"
#include "scheduler.pb.h"


SchedulerService::SchedulerService() {}

SchedulerService::~SchedulerService() {}

int SchedulerService::PHXEcho(const google::protobuf::StringValue &/* req */,
                              google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int SchedulerService::GetAddrScale(const phxqueue::comm::proto::GetAddrScaleRequest &/* req */,
                                   phxqueue::comm::proto::GetAddrScaleResponse */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: GetAddrScale unimplemented");
    return -1;
}


//gzrd_Lib_CPP_Version_ID--start
#ifndef GZRD_SVN_ATTR
#define GZRD_SVN_ATTR "0"
#endif
static char gzrd_Lib_CPP_Version_ID[] __attribute__((used))="$HeadURL: http://scm-gy.tencent.com/gzrd/gzrd_mail_rep/phoenix_proj/trunk/phxqueue/phxqueue_phxrpc/src/scheduler/phxrpc_scheduler_service.cpp $ $Id: phxrpc_scheduler_service.cpp 2143928 2017-06-29 09:20:49Z walnuthe $ " GZRD_SVN_ATTR "__file__";
// gzrd_Lib_CPP_Version_ID--end

