/* phxrpc_scheduler_stub.h

 Generated by phxrpc_pb2client from scheduler.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "scheduler.pb.h"


namespace phxrpc {


class BaseTcpStream;
class ClientMonitor;


}


class SchedulerStub {
  public:
    SchedulerStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor);
    ~SchedulerStub();

    void SetKeepAlive(const bool keep_alive);

    int PHXEcho(const google::protobuf::StringValue &req,
                google::protobuf::StringValue *resp);

    int GetAddrScale(const phxqueue::comm::proto::GetAddrScaleRequest &req,
                     phxqueue::comm::proto::GetAddrScaleResponse *resp);

  private:
    phxrpc::BaseTcpStream &socket_;
    phxrpc::ClientMonitor &client_monitor_;
    bool keep_alive_;
};

