/* phxrpc_scheduler_tool.h

 Generated by phxrpc_pb2tool from scheduler.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class SchedulerTool {
  public:
    SchedulerTool();
    virtual ~SchedulerTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);

    virtual int GetAddrScale(phxrpc::OptMap &bigmap);

    typedef int (SchedulerTool::*ToolFunc_t) (phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        SchedulerTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            { "PHXEcho", &SchedulerTool::PHXEcho, "c:f:vs:", "-s <string>" },
            { NULL, NULL }
        };

        return name2func;
    };
};

