/*
Tencent is pleased to support the open source community by making PhxQueue available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the BSD 3-Clause License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

<https://opensource.org/licenses/BSD-3-Clause>

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/



/* phxrpc_scheduler_stub.cpp

 Generated by phxrpc_pb2client from scheduler.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_scheduler_stub.h"

#include "phxrpc/rpc.h"
#include "phxrpc/network.h"


SchedulerStub::SchedulerStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor)
    : socket_(socket), client_monitor_(client_monitor), keep_alive_(false) {}

SchedulerStub::~SchedulerStub() {}

void SchedulerStub::SetKeepAlive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

int SchedulerStub::PhxEcho(const google::protobuf::StringValue &req,
                           google::protobuf::StringValue *resp) {
    phxrpc::HttpCaller caller(socket_, client_monitor_);
    caller.SetURI("/phxqueue_phxrpc.scheduler/PhxEcho", -1);
    caller.SetKeepAlive(keep_alive_);
    return caller.Call(req, resp);
}

int SchedulerStub::GetAddrScale(const phxqueue::comm::proto::GetAddrScaleRequest &req,
                                phxqueue::comm::proto::GetAddrScaleResponse *resp) {
    phxrpc::HttpCaller caller(socket_, client_monitor_);
    caller.SetURI("/phxqueue_phxrpc.scheduler/GetAddrScale", 1);
    caller.SetKeepAlive(keep_alive_);
    return caller.Call(req, resp);
}

