/* phxrpc_scheduler_dispatcher.h

 Generated by phxrpc_pb2service from scheduler.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_scheduler_dispatcher.h"

#include <errno.h>

#include "phxrpc/file.h"
#include "phxrpc/http.h"

#include "phxrpc_scheduler_service.h"
#include "scheduler.pb.h"


SchedulerDispatcher::SchedulerDispatcher(SchedulerService &service, phxrpc::DispatcherArgs_t *dispatcher_args)
    : service_(service), dispatcher_args_(dispatcher_args) {}

SchedulerDispatcher::~SchedulerDispatcher() {}

const phxrpc::HttpDispatcher< SchedulerDispatcher >::URIFuncMap &SchedulerDispatcher::GetURIFuncMap() {
    static phxrpc::HttpDispatcher< SchedulerDispatcher >::URIFuncMap uri_func_map = {
        {"/phxqueue_phxrpc.scheduler/PHXEcho", &SchedulerDispatcher::PHXEcho},
        {"/phxqueue_phxrpc.scheduler/GetAddrScale", &SchedulerDispatcher::GetAddrScale}};
    return uri_func_map;
}

int SchedulerDispatcher::PHXEcho(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response) {
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret = 0;

    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    //unpack request
    {
        if (!req.ParseFromString(request.GetContent())) {
            phxrpc::log(LOG_ERR, "ERROR: FromBuffer fail size %zu ip %s",
                request.GetContent().size(), request.GetClientIP());
            return -1 *EINVAL;
        }
    }

    //logic process
    {
        if (0 == ret) ret = service_.PHXEcho(req, &resp);
    }

    //pack response
    {
        if (!resp.SerializeToString(&(response->GetContent()))) {
            phxrpc::log(LOG_ERR, "ERROR: ToBuffer fail ip %s", request.GetClientIP());
            return -1 *ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: PHXEcho = %d", ret);

    return ret;
}

int SchedulerDispatcher::GetAddrScale(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response) {
    dispatcher_args_->server_monitor->SvrCall(1, "GetAddrScale", 1);

    int ret = 0;

    phxqueue::comm::proto::GetAddrScaleRequest req;
    phxqueue::comm::proto::GetAddrScaleResponse resp;

    //unpack request
    {
        if (!req.ParseFromString(request.GetContent())) {
            phxrpc::log(LOG_ERR, "ERROR: FromBuffer fail size %zu ip %s",
                request.GetContent().size(), request.GetClientIP());
            return -1 *EINVAL;
        }
    }

    //logic process
    {
        if (0 == ret) ret = service_.GetAddrScale(req, &resp);
    }

    //pack response
    {
        if (!resp.SerializeToString(&(response->GetContent()))) {
            phxrpc::log(LOG_ERR, "ERROR: ToBuffer fail ip %s", request.GetClientIP());
            return -1 *ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: GetAddrScale = %d", ret);

    return ret;
}


//gzrd_Lib_CPP_Version_ID--start
#ifndef GZRD_SVN_ATTR
#define GZRD_SVN_ATTR "0"
#endif
static char gzrd_Lib_CPP_Version_ID[] __attribute__((used))="$HeadURL: http://scm-gy.tencent.com/gzrd/gzrd_mail_rep/phoenix_proj/trunk/phxqueue/phxqueue_phxrpc/src/scheduler/phxrpc_scheduler_dispatcher.cpp $ $Id: phxrpc_scheduler_dispatcher.cpp 2143928 2017-06-29 09:20:49Z walnuthe $ " GZRD_SVN_ATTR "__file__";
// gzrd_Lib_CPP_Version_ID--end

