/* phxrpc_scheduler_dispatcher.h

 Generated by phxrpc_pb2service from scheduler.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"


class SchedulerService;


class SchedulerDispatcher {
  public:
    static const phxrpc::HttpDispatcher< SchedulerDispatcher >::URIFuncMap &GetURIFuncMap();

    SchedulerDispatcher(SchedulerService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    ~SchedulerDispatcher();

    int PHXEcho(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response);

    int GetAddrScale(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response);

  private:
    SchedulerService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

