/* scheduler_client.h

 Generated by phxrpc_pb2client from scheduler.proto

*/

#pragma once

#include "phxrpc/network.h"
#include "phxrpc/rpc.h"

#include "scheduler.pb.h"


class SchedulerClientUThread {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    SchedulerClientUThread(phxrpc::UThreadEpollScheduler *uthread_scheduler);
    virtual ~SchedulerClientUThread();

    int PHXEcho(const google::protobuf::StringValue &req,
                google::protobuf::StringValue *resp);

    int PhxBatchEcho(const google::protobuf::StringValue &req,
                     google::protobuf::StringValue *resp);

    int GetAddrScale(const phxqueue::comm::proto::GetAddrScaleRequest &req,
                     phxqueue::comm::proto::GetAddrScaleResponse *resp);



  private:
    phxrpc::UThreadEpollScheduler *uthread_scheduler_;
};

