/* scheduler_tool_main.cpp

 Generated by phxrpc_pb2tool from scheduler.proto

*/

#include <cstdlib>
#include <cstring>
#include <time.h>
#include <unistd.h>

#include "phxrpc/file.h"

#include "phxrpc_scheduler_tool.h"
#include "scheduler_client.h"
#include "scheduler_tool_impl.h"


using namespace phxrpc;


void ShowUsage(const char *program) {
    printf("\nUsage: %s [-c <config>] [-f <func>] [-v]\n", program);

    SchedulerTool::Name2Func_t *name2func = SchedulerTool::GetName2Func();

    for (int i = 0; ; i++) {
        SchedulerTool::Name2Func_t *iter = &(name2func[i]);

        if (NULL == iter->name) break;

        printf("    -f %s %s\n", iter->name, iter->usage);
    }
    printf("\n");
    exit(0);
}

int main(int argc, char *argv[]) {
    const char *func = NULL;
    const char *config = NULL;

    for (int i = 1; i < argc - 1; i++) {
        if (0 == strcmp(argv[i], "-c")) {
            config = argv[ ++i ];
        }
        if (0 == strcmp(argv[i], "-f")) {
            func = argv[ ++i ];
        }
        if (0 == strcmp(argv[i], "-v")) {
            ShowUsage(argv[0]);
        }
    }

    if (NULL == func) ShowUsage(argv[0]);

    if (NULL != config) SchedulerClient::Init(config);

    SchedulerTool::Name2Func_t *target = NULL;

    SchedulerTool::Name2Func_t *name2func = SchedulerTool::GetName2Func();

    for (int i = 0; i < 100; i++) {
        SchedulerTool::Name2Func_t *iter = &(name2func[i]);

        if (NULL == iter->name) break;

        if (0 == strcasecmp(func, iter->name)) {
            target = iter;
            break;
        }
    }

    if (NULL == target) ShowUsage(argv[0]);

    OptMap opt_map(target->opt_string);

    if (!opt_map.Parse(argc, argv)) ShowUsage(argv[0]);

    SchedulerTool::ToolFunc_t targefunc = target->func;

    SchedulerToolImpl tool;

    if (0 != (tool.*targefunc) (opt_map)) ShowUsage(argv[0]);

    return 0;
}

