/* scheduler_server_config.h

 Generated by phxrpc_pb2server from scheduler.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class SchedulerServerConfig {
  public:
    SchedulerServerConfig();

    ~SchedulerServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

    const char *GetTopic() const;
    const char *GetPhxQueueGlobalConfigPath() const;


  private:
    phxrpc::HshaServerConfig ep_server_config_;

    char topic_[128];
    char phxqueue_global_config_path_[128];
};

