/* lock_service_impl.h

 Generated by phxrpc_pb2service from lock.proto

*/

#pragma once

#include "phxqueue/lock.h"

#include "lock.pb.h"
#include "phxrpc_lock_service.h"


class LockServerConfig;


typedef struct tagServiceArgs {
    LockServerConfig *config;
    phxqueue::lock::Lock *lock;
} ServiceArgs_t;


class LockServiceImpl : public LockService {
  public:
    LockServiceImpl(ServiceArgs_t &app_args);
    virtual ~LockServiceImpl();

    virtual int PHXEcho(const google::protobuf::StringValue &req,
                        google::protobuf::StringValue *resp) override;

    virtual int GetLockInfo(const phxqueue::comm::proto::GetLockInfoRequest &req,
                            phxqueue::comm::proto::GetLockInfoResponse *resp) override;

    virtual int AcquireLock(const phxqueue::comm::proto::AcquireLockRequest &req,
                            phxqueue::comm::proto::AcquireLockResponse *resp) override;

  private:
    ServiceArgs_t &args_;
    phxqueue::lock::Lock *lock_{nullptr};
};

