/* lock_client.h

 Generated by phxrpc_pb2client from lock.proto

*/

#pragma once

#include "phxqueue/comm.h"
#include "phxrpc/rpc.h"

#include "lock.pb.h"


class LockClient {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    LockClient();
    virtual ~LockClient();

    int PHXEcho(const google::protobuf::StringValue &req,
                google::protobuf::StringValue *resp);

    int PhxBatchEcho(const google::protobuf::StringValue &req,
                     google::protobuf::StringValue *resp);

    int GetLockInfo(const phxqueue::comm::proto::GetLockInfoRequest &req,
                    phxqueue::comm::proto::GetLockInfoResponse *resp);

    int AcquireLock(const phxqueue::comm::proto::AcquireLockRequest &req,
                    phxqueue::comm::proto::AcquireLockResponse *resp);

    phxqueue::comm::RetCode
    ProtoGetLockInfo(const phxqueue::comm::proto::GetLockInfoRequest &req,
                     phxqueue::comm::proto::GetLockInfoResponse &resp);

    phxqueue::comm::RetCode
    ProtoAcquireLock(const phxqueue::comm::proto::AcquireLockRequest &req,
                     phxqueue::comm::proto::AcquireLockResponse &resp);
};

