/* lock_tool_main.cpp

 Generated by phxrpc_pb2tool from lock.proto

*/

#include <cstdlib>
#include <cstring>
#include <time.h>
#include <unistd.h>

#include "phxrpc/file.h"

#include "lock_client.h"
#include "lock_tool_impl.h"
#include "phxrpc_lock_tool.h"


using namespace phxrpc;


void ShowUsage(const char *program) {
    printf("\nUsage: %s [-c <config>] [-f <func>] [-v]\n", program);

    LockTool::Name2Func_t *name2func{LockTool::GetName2Func()};

    for (int i{0}; ; ++i) {
        LockTool::Name2Func_t *iter = &(name2func[i]);

        if( NULL == iter->name ) break;

        printf("    -f %s %s\n", iter->name, iter->usage);
    }
    printf("\n");
    exit(0);
}

int main(int argc, char *argv[]) {
    const char *func{nullptr};
    const char *config{nullptr};

    for (int i{1}; i < argc - 1; ++i) {
        if (0 == strcmp(argv[i], "-c")) {
            config = argv[++i];
        }
        if (0 == strcmp(argv[i], "-f")) {
            func = argv[++i];
        }
        if (0 == strcmp(argv[i], "-v")) {
            ShowUsage(argv[0]);
        }
    }

    if (nullptr == func) ShowUsage(argv[0]);

    if (nullptr != config) LockClient::Init(config);

    LockTool::Name2Func_t *target{nullptr};

    LockTool::Name2Func_t *name2func{LockTool::GetName2Func()};

    for (int i{0}; i < 100; ++i) {
        LockTool::Name2Func_t * iter = &( name2func[i] );

        if (nullptr == iter->name) break;

        if (0 == strcasecmp(func, iter->name)) {
            target = iter;
            break;
        }
    }

    if (nullptr == target) ShowUsage(argv[0]);

    OptMap opt_map(target->opt_string);

    if (!opt_map.Parse(argc, argv)) ShowUsage(argv[0]);

    LockTool::ToolFunc_t targefunc{target->func};

    LockToolImpl tool;

    if (0 != (tool.*targefunc)(opt_map)) ShowUsage(argv[0]);

    return 0;
}

