/* lock_service_impl.cpp

 Generated by phxrpc_pb2service from lock.proto

*/

#include "lock_service_impl.h"

#include "phxrpc/file.h"

#include "lock_server_config.h"


LockServiceImpl::LockServiceImpl(ServiceArgs_t &app_args) : args_(app_args), lock_(app_args.lock) {}


LockServiceImpl::~LockServiceImpl() {}

int LockServiceImpl::PHXEcho(const google::protobuf::StringValue &req,
                             google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int LockServiceImpl::GetLockInfo(const phxqueue::comm::proto::GetLockInfoRequest &req,
                                 phxqueue::comm::proto::GetLockInfoResponse *resp) {
    int ret{static_cast<int>(lock_->GetLockInfo(req, *resp))};

    if (0 != ret) {
        QLErr("Lock GetLockInfo err %d", ret);
    }

    return ret;
}

int LockServiceImpl::AcquireLock(const phxqueue::comm::proto::AcquireLockRequest &req,
                                 phxqueue::comm::proto::AcquireLockResponse *resp) {
    int ret{static_cast<int>(lock_->AcquireLock(req, *resp))};

    if (0 != ret) {
        QLErr("Lock AcquireLock err %d", ret);
    }

    return ret;
}



//gzrd_Lib_CPP_Version_ID--start
#ifndef GZRD_SVN_ATTR
#define GZRD_SVN_ATTR "0"
#endif
static char gzrd_Lib_CPP_Version_ID[] __attribute__((used))="$HeadURL: http://scm-gy.tencent.com/gzrd/gzrd_mail_rep/phoenix_proj/trunk/phxqueue/phxqueue_phxrpc/src/lock/lock_service_impl.cpp $ $Id: lock_service_impl.cpp 2144319 2017-06-29 12:19:19Z walnuthe $ " GZRD_SVN_ATTR "__file__";
// gzrd_Lib_CPP_Version_ID--end

