/* lock_tool_impl.h

 Generated by phxrpc_pb2tool from lock.proto

*/

#pragma once

#include <cstdio>

#include "phxrpc_lock_tool.h"


namespace phxrpc {


class OptMap;


}


class LockToolImpl : public LockTool {
  public:
    LockToolImpl();
    virtual ~LockToolImpl();

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;

    virtual int GetLockInfo(phxrpc::OptMap &opt_map) override;

    virtual int AcquireLock(phxrpc::OptMap &opt_map) override;
};

