/*
Tencent is pleased to support the open source community by making PhxQueue available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the BSD 3-Clause License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

<https://opensource.org/licenses/BSD-3-Clause>

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/



/* phxrpc_lock_service.h

 Generated by phxrpc_pb2service from lock.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "lock.pb.h"


class LockService {
  public:
    LockService();
    virtual ~LockService();

    virtual int PHXEcho(const google::protobuf::StringValue &req,
                        google::protobuf::StringValue *resp);

    virtual int GetString(const phxqueue::comm::proto::GetStringRequest &req,
                          phxqueue::comm::proto::GetStringResponse *resp);

    virtual int SetString(const phxqueue::comm::proto::SetStringRequest &req,
                          phxqueue::comm::proto::SetStringResponse *resp);

    virtual int DeleteString(const phxqueue::comm::proto::DeleteStringRequest &req,
                             phxqueue::comm::proto::DeleteStringResponse *resp);

    virtual int GetLockInfo(const phxqueue::comm::proto::GetLockInfoRequest &req,
                            phxqueue::comm::proto::GetLockInfoResponse *resp);

    virtual int AcquireLock(const phxqueue::comm::proto::AcquireLockRequest &req,
                            phxqueue::comm::proto::AcquireLockResponse *resp);

};

