/* phxrpc_lock_tool.h

 Generated by phxrpc_pb2tool from lock.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class LockTool {
  public:
    LockTool();
    virtual ~LockTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);

    virtual int GetLockInfo(phxrpc::OptMap &bigmap);

    virtual int AcquireLock(phxrpc::OptMap &bigmap);

  public:
    typedef int (LockTool::*ToolFunc_t) (phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        LockTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            { "PHXEcho", &LockTool::PHXEcho, "c:f:vs:", "-s <string>" },
            { NULL, NULL }
        };

        return name2func;
    };
};

