/* phxrpc_lock_dispatcher.h

 Generated by phxrpc_pb2service from lock.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"


class LockService;


class LockDispatcher {
  public:
    static const phxrpc::HttpDispatcher< LockDispatcher >::URIFuncMap &GetURIFuncMap();

    LockDispatcher(LockService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    ~LockDispatcher();

    int PHXEcho(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response);

    int GetLockInfo(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response);

    int AcquireLock(const phxrpc::HttpRequest &request, phxrpc::HttpResponse *response);

  private:
    LockService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

