/* phxrpc_lock_service.cpp

 Generated by phxrpc_pb2service from lock.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc/file.h"

#include "lock.pb.h"
#include "phxrpc_lock_service.h"


LockService::LockService() {}

LockService::~LockService() {}

int LockService::PHXEcho(const google::protobuf::StringValue &/* req */,
        google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int LockService::GetLockInfo(const phxqueue::comm::proto::GetLockInfoRequest &/* req */,
                             phxqueue::comm::proto::GetLockInfoResponse */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: GetLockInfo unimplemented");
    return -1;
}

int LockService::AcquireLock(const phxqueue::comm::proto::AcquireLockRequest &/* req */,
                             phxqueue::comm::proto::AcquireLockResponse */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: AcquireLock unimplemented");
    return -1;
}


//gzrd_Lib_CPP_Version_ID--start
#ifndef GZRD_SVN_ATTR
#define GZRD_SVN_ATTR "0"
#endif
static char gzrd_Lib_CPP_Version_ID[] __attribute__((used))="$HeadURL: http://scm-gy.tencent.com/gzrd/gzrd_mail_rep/phoenix_proj/trunk/phxqueue/phxqueue_phxrpc/src/lock/phxrpc_lock_service.cpp $ $Id: phxrpc_lock_service.cpp 2143928 2017-06-29 09:20:49Z walnuthe $ " GZRD_SVN_ATTR "__file__";
// gzrd_Lib_CPP_Version_ID--end

