/*
Tencent is pleased to support the open source community by making PhxQueue available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the BSD 3-Clause License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

<https://opensource.org/licenses/BSD-3-Clause>

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/



/* phxrpc_store_tool.cpp

 Generated by phxrpc_pb2tool from store.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_store_tool.h"

#include "phxrpc/file.h"

#include "store_client.h"


using namespace phxrpc;


StoreTool::StoreTool() {}

StoreTool::~StoreTool() {}

int StoreTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int StoreTool::Add(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Add unimplement ***\n");

    return -1;
}

int StoreTool::Get(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Get unimplement ***\n");

    return -1;
}

