/* phxrpc_store_service.h

 Generated by phxrpc_pb2service from store.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "store.pb.h"


class StoreService {
  public:
    StoreService();
    virtual ~StoreService();

    virtual int PHXEcho(const google::protobuf::StringValue &req,
                        google::protobuf::StringValue *resp);

    virtual int Add(const phxqueue::comm::proto::AddRequest &req,
                    phxqueue::comm::proto::AddResponse *resp);

    virtual int Get(const phxqueue::comm::proto::GetRequest &req,
                    phxqueue::comm::proto::GetResponse *resp);
};

