/* phxrpc_store_tool.cpp

 Generated by phxrpc_pb2tool from store.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_store_tool.h"

#include "phxrpc/file.h"

#include "store_client.h"


using namespace phxrpc;


StoreTool::StoreTool() {}

StoreTool::~StoreTool() {}

int StoreTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int StoreTool::Add(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Add unimplement ***\n");

    return -1;
}

int StoreTool::Get(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Get unimplement ***\n");

    return -1;
}

