/* phxrpc_store_tool.h

 Generated by phxrpc_pb2tool from store.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class StoreTool {
  public:
    StoreTool();
    virtual ~StoreTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);

    virtual int Add(phxrpc::OptMap &bigmap);

    virtual int Get(phxrpc::OptMap &bigmap);

    typedef int (StoreTool::*ToolFunc_t) (phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        StoreTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            { "PHXEcho", &StoreTool::PHXEcho, "c:f:vs:", "-s <string>" },
            { nullptr, nullptr }
        };

        return name2func;
    };
};

