/* store_server_config.h

 Generated by phxrpc_pb2server from store.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class StoreServerConfig {
  public:
    StoreServerConfig();

    ~StoreServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

    const char *GetTopic() const;
    const char *GetDataDirPath() const;
    const char *GetPhxQueueGlobalConfigPath() const;
    int GetPaxosPort() const;
    int GetNPaxosIOThread() const;

  private:
    phxrpc::HshaServerConfig ep_server_config_;

    char topic_[128];
    char data_dir_path_[128];
    char phxqueue_global_config_path_[128];
    int paxos_port_;
    int npaxos_iothread_;

};

