/* store_service_impl.h

 Generated by phxrpc_pb2service from store.proto

*/

#pragma once

#include "phxqueue/store.h"

#include "phxrpc_store_service.h"
#include "store.pb.h"


class StoreServerConfig;


typedef struct tagServiceArgs {
    StoreServerConfig *config;
    phxqueue::store::Store *store;
} ServiceArgs_t;


class StoreServiceImpl : public StoreService {
  public:
    StoreServiceImpl(ServiceArgs_t &app_args);
    virtual ~StoreServiceImpl();

    virtual int PHXEcho(const google::protobuf::StringValue &req,
                        google::protobuf::StringValue *resp) override;

    virtual int Add(const phxqueue::comm::proto::AddRequest &req,
                    phxqueue::comm::proto::AddResponse *resp) override;

    virtual int Get(const phxqueue::comm::proto::GetRequest &req,
                    phxqueue::comm::proto::GetResponse *resp) override;

  private:
    ServiceArgs_t &args_;
    phxqueue::store::Store *store_{nullptr};
};

