/*
Tencent is pleased to support the open source community by making PhxQueue available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the BSD 3-Clause License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

<https://opensource.org/licenses/BSD-3-Clause>

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/



/* store_tool_impl.h

 Generated by phxrpc_pb2tool from store.proto

*/

#pragma once

#include <cstdio>

#include "phxrpc_store_tool.h"


namespace phxrpc {


class OptMap;


}


class StoreToolImpl : public StoreTool {
  public:
    StoreToolImpl();
    virtual ~StoreToolImpl();

    virtual int PHXEcho(phxrpc::OptMap &opt_map);

    virtual int Add(phxrpc::OptMap &opt_map) override;

    virtual int Get(phxrpc::OptMap &opt_map) override;
};

