/* store_service_impl.cpp

 Generated by phxrpc_pb2service from store.proto

*/

#include "store_service_impl.h"

#include "phxrpc/file.h"

#include "store_server_config.h"


StoreServiceImpl::StoreServiceImpl(ServiceArgs_t &app_args) : args_(app_args), store_(app_args.store) {}

StoreServiceImpl::~StoreServiceImpl() {}

int StoreServiceImpl::PHXEcho(const google::protobuf::StringValue &req,
                              google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int StoreServiceImpl::Add(const phxqueue::comm::proto::AddRequest &req,
                          phxqueue::comm::proto::AddResponse *resp) {
    int ret{static_cast<int>(store_->Add(req, *resp))};

    if (0 > ret) {
        QLErr("Store Add err %d", ret);
    }

    return ret;
}

int StoreServiceImpl::Get(const phxqueue::comm::proto::GetRequest &req,
                          phxqueue::comm::proto::GetResponse *resp) {
    int ret{static_cast<int>(store_->Get(req, *resp))};

    if (0 > ret) {
        QLErr("Store Get err %d", ret);
    }

    return ret;
}



//gzrd_Lib_CPP_Version_ID--start
#ifndef GZRD_SVN_ATTR
#define GZRD_SVN_ATTR "0"
#endif
static char gzrd_Lib_CPP_Version_ID[] __attribute__((used))="$HeadURL$ $Id$ " GZRD_SVN_ATTR "__file__";
// gzrd_Lib_CPP_Version_ID--end

