/*
Tencent is pleased to support the open source community by making PhxQueue available.
Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the BSD 3-Clause License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

<https://opensource.org/licenses/BSD-3-Clause>

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/



/* store_service_impl.cpp

 Generated by phxrpc_pb2service from store.proto

*/

#include "store_service_impl.h"

#include "phxrpc/file.h"

#include "store_server_config.h"


StoreServiceImpl::StoreServiceImpl(ServiceArgs_t &app_args) : args_(app_args), store_(app_args.store) {}

StoreServiceImpl::~StoreServiceImpl() {}

int StoreServiceImpl::PHXEcho(const google::protobuf::StringValue &req,
                              google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int StoreServiceImpl::Add(const phxqueue::comm::proto::AddRequest &req,
                          phxqueue::comm::proto::AddResponse *resp) {
    int ret{static_cast<int>(store_->Add(req, *resp))};

    if (0 > ret) {
        QLErr("Store Add err %d", ret);
    }

    return ret;
}

int StoreServiceImpl::Get(const phxqueue::comm::proto::GetRequest &req,
                          phxqueue::comm::proto::GetResponse *resp) {
    int ret{static_cast<int>(store_->Get(req, *resp))};

    if (0 > ret) {
        QLErr("Store Get err %d", ret);
    }

    return ret;
}

