/* mqttbroker_tool_impl.h

 Generated by phxrpc_pb2tool from mqttbroker.proto

*/

#pragma once

#include "phxrpc_mqttbroker_tool.h"


namespace phxrpc {


class OptMap;


}


class MqttBrokerToolImpl : public MqttBrokerTool {
  public:
    MqttBrokerToolImpl();
    virtual ~MqttBrokerToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int HttpPublish(phxrpc::OptMap &opt_map) override;
    virtual int MqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int MqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int MqttPuback(phxrpc::OptMap &opt_map) override;
    virtual int MqttPubrec(phxrpc::OptMap &opt_map) override;
    virtual int MqttPubrel(phxrpc::OptMap &opt_map) override;
    virtual int MqttPubcomp(phxrpc::OptMap &opt_map) override;
    virtual int MqttSubscribe(phxrpc::OptMap &opt_map) override;
    virtual int MqttUnsubscribe(phxrpc::OptMap &opt_map) override;
    virtual int MqttPing(phxrpc::OptMap &opt_map) override;
    virtual int MqttDisconnect(phxrpc::OptMap &opt_map) override;
};

