/* phxrpc_search_tool.cpp

 Generated by phxrpc_pb2tool from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc/file.h"

#include "phxrpc_search_tool.h"
#include "search_client.h"


using namespace phxrpc;


SearchTool::SearchTool() {
}

SearchTool::~SearchTool() {
}

// http protocol

int SearchTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int SearchTool::PhxHttpPublish(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxHttpPublish unimplement ***\n");

    return -1;
}

// mqtt protocol

int SearchTool::PhxMqttConnect(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttConnect unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttPublish(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttPublish unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttPuback(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttPuback unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttPubrec(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttPubrec unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttPubrel(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttPubrel unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttPubcomp(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttPubcomp unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttSubscribe(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttSubscribe unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttUnsubscribe(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttUnsubscribe unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttPing(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttPing unimplement ***\n");

    return -1;
}

int SearchTool::PhxMqttDisconnect(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PhxMqttDisconnect unimplement ***\n");

    return -1;
}

