/* phxrpc_search_tool.cpp

 Generated by phxrpc_pb2tool from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc/file.h"

#include "phxrpc_search_tool.h"
#include "search_client.h"


using namespace phxrpc;


SearchTool::SearchTool() {
}

SearchTool::~SearchTool() {
}

// http protocol

int SearchTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int SearchTool::HttpPublish(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** HttpPublish unimplement ***\n");

    return -1;
}

// mqtt protocol

int SearchTool::MqttConnect(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttConnect unimplement ***\n");

    return -1;
}

int SearchTool::MqttPublish(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttPublish unimplement ***\n");

    return -1;
}

int SearchTool::MqttPuback(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttPuback unimplement ***\n");

    return -1;
}

int SearchTool::MqttPubrec(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttPubrec unimplement ***\n");

    return -1;
}

int SearchTool::MqttPubrel(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttPubrel unimplement ***\n");

    return -1;
}

int SearchTool::MqttPubcomp(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttPubcomp unimplement ***\n");

    return -1;
}

int SearchTool::MqttSubscribe(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttSubscribe unimplement ***\n");

    return -1;
}

int SearchTool::MqttUnsubscribe(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttUnsubscribe unimplement ***\n");

    return -1;
}

int SearchTool::MqttPing(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttPing unimplement ***\n");

    return -1;
}

int SearchTool::MqttDisconnect(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** MqttDisconnect unimplement ***\n");

    return -1;
}

