/* phxrpc_search_tool.h

 Generated by phxrpc_pb2tool from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class SearchTool {
  public:
    SearchTool();
    virtual ~SearchTool();

    // http protocol
    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int HttpPublish(phxrpc::OptMap &bigmap);

    // mqtt protocol
    virtual int MqttConnect(phxrpc::OptMap &bigmap);
    virtual int MqttPublish(phxrpc::OptMap &bigmap);
    virtual int MqttPuback(phxrpc::OptMap &bigmap);
    virtual int MqttPubrec(phxrpc::OptMap &bigmap);
    virtual int MqttPubrel(phxrpc::OptMap &bigmap);
    virtual int MqttPubcomp(phxrpc::OptMap &bigmap);
    virtual int MqttSubscribe(phxrpc::OptMap &bigmap);
    virtual int MqttUnsubscribe(phxrpc::OptMap &bigmap);
    virtual int MqttPing(phxrpc::OptMap &bigmap);
    virtual int MqttDisconnect(phxrpc::OptMap &bigmap);

    typedef int (SearchTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        SearchTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &SearchTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"HttpPublish", &SearchTool::HttpPublish, "c:f:vx:y:d:q:r:t:p:s:",
                    "-x <pub_client_id> -y <sub_client_id> -d <dup> -q <qos> -r <retain> -t <topic_name> -p <packet_identifier> -s <string>"},
            {"MqttConnect", &SearchTool::MqttConnect, "c:f:vl:",
                    "-l <client_identifier>"},
            {"MqttPublish", &SearchTool::MqttPublish, "c:f:vl:d:q:r:t:p:s:",
                    "-l <client_identifier> -d <dup> -q <qos> -r <retain> -t <topic_name> -p <packet_identifier> -s <string>"},
            {"MqttPuback", &SearchTool::MqttPuback, "c:f:vl:p:",
                    "-l <client_identifier> -p <packet_identifier>"},
            {"MqttSubscribe", &SearchTool::MqttSubscribe, "c:f:vl:p:t:q:",
                    "-l <client_identifier> -p <packet_identifier> -t <topic_filters> -q <qoss>"},
            {"MqttUnsubscribe", &SearchTool::MqttUnsubscribe, "c:f:vl:p:t:",
                    "-l <client_identifier> -p <packet_identifier> -t <topic_filters>"},
            {"MqttPing", &SearchTool::MqttPing, "c:f:vl:",
                    "-l <client_identifier>"},
            {"MqttDisconnect", &SearchTool::MqttDisconnect, "c:f:vl:",
                    "-l <client_identifier>"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

