/* phxrpc_search_stub.cpp

 Generated by phxrpc_pb2client from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_search_stub.h"

#include "phxrpc/rpc.h"
#include "phxrpc/network.h"


using namespace phxqueue_phxrpc::logic::mqtt;


SearchStub::SearchStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
                       phxrpc::BaseMessageHandlerFactory &msg_handler_factory)
        : socket_(socket), client_monitor_(client_monitor),
          msg_handler_factory_(msg_handler_factory) {
}

SearchStub::~SearchStub() {
}

void SearchStub::set_keep_alive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

// http protocol

int SearchStub::PHXEcho(const google::protobuf::StringValue &req,
                        google::protobuf::StringValue *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/PHXEcho", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::HttpPublish(const HttpPublishPb &req, HttpPubackPb *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/HttpPublish", 2000031);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

// mqtt protocol

int SearchStub::MqttConnect(const MqttConnectPb &req, MqttConnackPb *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttConnect", 2000011);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttPublish(const MqttPublishPb &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttPublish", 2000012);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttPuback(const MqttPubackPb &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttPuback", 2000013);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttPubrec(const MqttPubrecPb &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttPubrec", 2000014);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttPubrel(const MqttPubrelPb &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttPubrel", 2000015);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttPubcomp(const MqttPubcompPb &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttPubcomp", 2000016);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttSubscribe(const MqttSubscribePb &req, MqttSubackPb *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttSubscribe", 2000017);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttUnsubscribe(const MqttUnsubscribePb &req, MqttUnsubackPb *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttUnsubscribe", 2000018);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttPing(const MqttPingreqPb &req, MqttPingrespPb *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttPing", 2000019);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::MqttDisconnect(const MqttDisconnectPb &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/phxqueue_phxrpc/mqttbroker/MqttDisconnect", 2000020);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

