/* phxrpc_search_stub.h

 Generated by phxrpc_pb2client from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "mqttbroker.pb.h"


namespace phxrpc {


class BaseMessageHandlerFactory;
class BaseTcpStream;
class ClientMonitor;


}


class SearchStub {
  public:
    SearchStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
               phxrpc::BaseMessageHandlerFactory &msg_handler_factory);
    virtual ~SearchStub();

    void set_keep_alive(const bool keep_alive);

    // http protocol
    int PHXEcho(const google::protobuf::StringValue &req,
                google::protobuf::StringValue *resp);
    int PhxHttpPublish(const phxqueue_phxrpc::mqttbroker::HttpPublishPb &req,
                       phxqueue_phxrpc::mqttbroker::HttpPubackPb *resp);

    // mqtt protocol
    int PhxMqttConnect(const phxqueue_phxrpc::mqttbroker::MqttConnectPb &req,
                       phxqueue_phxrpc::mqttbroker::MqttConnackPb *resp);
    int PhxMqttPublish(const phxqueue_phxrpc::mqttbroker::MqttPublishPb &req,
                       google::protobuf::Empty *resp);
    int PhxMqttPuback(const phxqueue_phxrpc::mqttbroker::MqttPubackPb &req,
                      google::protobuf::Empty *resp);
    int PhxMqttPubrec(const phxqueue_phxrpc::mqttbroker::MqttPubrecPb &req,
                      google::protobuf::Empty *resp);
    int PhxMqttPubrel(const phxqueue_phxrpc::mqttbroker::MqttPubrelPb &req,
                      google::protobuf::Empty *resp);
    int PhxMqttPubcomp(const phxqueue_phxrpc::mqttbroker::MqttPubcompPb &req,
                       google::protobuf::Empty *resp);
    int PhxMqttSubscribe(const phxqueue_phxrpc::mqttbroker::MqttSubscribePb &req,
                         phxqueue_phxrpc::mqttbroker::MqttSubackPb *resp);
    int PhxMqttUnsubscribe(const phxqueue_phxrpc::mqttbroker::MqttUnsubscribePb &req,
                           phxqueue_phxrpc::mqttbroker::MqttUnsubackPb *resp);
    int PhxMqttPing(const phxqueue_phxrpc::mqttbroker::MqttPingreqPb &req,
                    phxqueue_phxrpc::mqttbroker::MqttPingrespPb *resp);
    int PhxMqttDisconnect(const phxqueue_phxrpc::mqttbroker::MqttDisconnectPb &req,
                          google::protobuf::Empty *resp);

  private:
    phxrpc::BaseTcpStream &socket_;
    phxrpc::ClientMonitor &client_monitor_;
    phxrpc::BaseMessageHandlerFactory &msg_handler_factory_;
    bool keep_alive_;
};

