/* search_client.cpp

 Generated by phxrpc_pb2client from search.proto

*/



#include "search_client.h"

#include <cstdlib>
#include <memory>
#include <mutex>

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"

#include "phxrpc_search_stub.h"
#include "resource_pool.h"


using namespace phxqueue_phxrpc::logic::mqtt;
using namespace std;


static phxrpc::ClientConfig global_searchclient_config_;
static phxrpc::ClientMonitorPtr global_searchclient_monitor_;


bool SearchClient::Init(const char *config_file) {
    return global_searchclient_config_.Read(config_file);
}

const char *SearchClient::GetPackageName() {
    const char *ret = global_searchclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "search";
    }
    return ret;
}

SearchClient::SearchClient() {
    static mutex monitor_mutex;
    if (!global_searchclient_monitor_.get()) {
        monitor_mutex.lock();
        if (!global_searchclient_monitor_.get()) {
            global_searchclient_monitor_ = phxrpc::MonitorFactory::GetFactory()->
                    CreateClientMonitor(GetPackageName());
        }
        global_searchclient_config_.SetClientMonitor(global_searchclient_monitor_);
        monitor_mutex.unlock();
    }
}

SearchClient::~SearchClient() {
}

// http protocol

int SearchClient::PHXEcho(const google::protobuf::StringValue &req,
                          google::protobuf::StringValue *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.PHXEcho(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::HttpPublish(const HttpPublishPb &req, HttpPubackPb *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.HttpPublish(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

// mqtt protocol

int SearchClient::MqttConnect(const MqttConnectPb &req, MqttConnackPb *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttConnect(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttPublish(const MqttPublishPb &req, google::protobuf::Empty *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttPublish(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttPuback(const MqttPubackPb &req, google::protobuf::Empty *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttPuback(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttPubrec(const MqttPubrecPb &req, google::protobuf::Empty *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttPubrec(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttPubrel(const MqttPubrelPb &req, google::protobuf::Empty *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttPubrel(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttPubcomp(const MqttPubcompPb &req, google::protobuf::Empty *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttPubcomp(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttSubscribe(const MqttSubscribePb &req, MqttSubackPb *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttSubscribe(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttUnsubscribe(const MqttUnsubscribePb &req, MqttUnsubackPb *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttUnsubscribe(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttPing(const MqttPingreqPb &req, MqttPingrespPb *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttPing(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

int SearchClient::MqttDisconnect(const MqttDisconnectPb &req, google::protobuf::Empty *resp) {
    const phxrpc::Endpoint_t *ep = global_searchclient_config_.GetRandom();

    if (ep) {
        auto &&socket_pool(ResourcePool<uint64_t, phxrpc::BlockTcpStream>::GetInstance());
        // TODO:
        uint64_t key(ep->port);
        auto socket = move(socket_pool->Get(key));

        if (nullptr == socket.get()) {
            socket.reset(new phxrpc::BlockTcpStream());

            bool open_ret{phxrpc::PhxrpcTcpUtils::Open(socket.get(), ep->ip, ep->port,
                    global_searchclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                    *(global_searchclient_monitor_.get()))};
            if (!open_ret) {
                phxrpc::log(LOG_ERR, "Open %s:%d err %d", ep->ip, ep->port, open_ret);

                return -1;
            }
            socket->SetTimeout(global_searchclient_config_.GetSocketTimeoutMS());
        }

        phxrpc::HttpMessageHandlerFactory http_msg_factory;
        SearchStub stub(*(socket.get()), *(global_searchclient_monitor_.get()), http_msg_factory);
        int ret{stub.MqttDisconnect(req, resp)};
        socket_pool->Put(key, socket);

        return ret;
    }

    return -1;
}

