/* search_tool_impl.h

 Generated by phxrpc_pb2tool from search.proto

*/

#pragma once

#include "phxrpc_search_tool.h"


namespace phxrpc {


class OptMap;


}


class SearchToolImpl : public SearchTool {
  public:
    SearchToolImpl();
    virtual ~SearchToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int PhxHttpPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPuback(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPubrec(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPubrel(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPubcomp(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttSubscribe(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttUnsubscribe(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPing(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttDisconnect(phxrpc::OptMap &opt_map) override;
};

