/* search_tool_main.cpp

 Generated by phxrpc_pb2tool from search.proto

*/

#include <cstdlib>
#include <cstring>
#include <ctime>
#include <unistd.h>

#include "phxrpc_search_tool.h"
#include "search_tool_impl.h"

#include "search_client.h"

#include "phxrpc/file.h"


using namespace phxrpc;


void ShowUsage(const char *program) {
    printf("\nUsage: %s [-c <config>] [-f <func>] [-v]\n", program);

    SearchTool::Name2Func_t *name2func = SearchTool::GetName2Func();

    for (int i{0}; ; ++i) {
        SearchTool::Name2Func_t *iter = &(name2func[i]);

        if (nullptr == iter->name) break;

        printf("    -f %s %s\n", iter->name, iter->usage);
    }
    printf("\n");
    exit(0);
}

int main(int argc, char **argv) {
    const char *func{nullptr};
    const char *config{nullptr};

    for (int i{1}; argc - 1 > i; ++i) {
        if (0 == strcmp(argv[i], "-c")) {
            config = argv[++i];
        }
        if (0 == strcmp(argv[i], "-f")) {
            func = argv[++i];
        }
        if (0 == strcmp(argv[i], "-v")) {
            ShowUsage(argv[0]);
        }
    }

    if (nullptr == func) ShowUsage(argv[0]);

    if (nullptr != config) SearchClient::Init(config);

    SearchTool::Name2Func_t *target{nullptr};

    SearchTool::Name2Func_t *name2func{SearchTool::GetName2Func()};

    for (int i{0}; 100 > i; ++i) {
        SearchTool::Name2Func_t *iter = &(name2func[i]);

        if (nullptr == iter->name) break;

        if (0 == strcasecmp(func, iter->name)) {
            target = iter;
            break;
        }
    }

    if (nullptr == target) ShowUsage(argv[0]);

    OptMap opt_map(target->opt_string);

    if (!opt_map.Parse(argc, argv)) ShowUsage(argv[0]);

    SearchTool::ToolFunc_t targefunc = target->func;

    SearchToolImpl tool;

    if (0 != (tool.*targefunc)(opt_map)) ShowUsage(argv[0]);

    return 0;
}

