/* phxrpc_mqttbroker_tool.h

 Generated by phxrpc_pb2tool from mqttbroker.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class MqttBrokerTool {
  public:
    MqttBrokerTool();
    virtual ~MqttBrokerTool();

    // http protocol
    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int HttpPublish(phxrpc::OptMap &bigmap);

    // mqtt protocol
    virtual int MqttConnect(phxrpc::OptMap &bigmap);
    virtual int MqttPublish(phxrpc::OptMap &bigmap);
    virtual int MqttPuback(phxrpc::OptMap &bigmap);
    virtual int MqttPubrec(phxrpc::OptMap &bigmap);
    virtual int MqttPubrel(phxrpc::OptMap &bigmap);
    virtual int MqttPubcomp(phxrpc::OptMap &bigmap);
    virtual int MqttSubscribe(phxrpc::OptMap &bigmap);
    virtual int MqttUnsubscribe(phxrpc::OptMap &bigmap);
    virtual int MqttPing(phxrpc::OptMap &bigmap);
    virtual int MqttDisconnect(phxrpc::OptMap &bigmap);
    virtual int ProtoHttpPublish(phxrpc::OptMap &opt_map);

    typedef int (MqttBrokerTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        MqttBrokerTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &MqttBrokerTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"HttpPublish", &MqttBrokerTool::HttpPublish, "c:f:vx:y:d:q:r:t:p:s:",
                    "-x <pub_client_id> -y <sub_client_id> -d <dup> -q <qos> -r <retain> -t <topic_name> -p <packet_identifier> -s <string>"},
            {"MqttConnect", &MqttBrokerTool::MqttConnect, "c:f:vl:",
                    "-l <client_identifier>"},
            {"MqttPublish", &MqttBrokerTool::MqttPublish, "c:f:vl:d:q:r:t:p:s:",
                    "-l <client_identifier> -d <dup> -q <qos> -r <retain> -t <topic_name> -p <packet_identifier> -s <string>"},
            {"MqttPuback", &MqttBrokerTool::MqttPuback, "c:f:vl:p:",
                    "-l <client_identifier> -p <packet_identifier>"},
            {"MqttSubscribe", &MqttBrokerTool::MqttSubscribe, "c:f:vl:p:t:q:",
                    "-l <client_identifier> -p <packet_identifier> -t <topic_filters> -q <qoss>"},
            {"MqttUnsubscribe", &MqttBrokerTool::MqttUnsubscribe, "c:f:vl:p:t:",
                    "-l <client_identifier> -p <packet_identifier> -t <topic_filters>"},
            {"MqttPing", &MqttBrokerTool::MqttPing, "c:f:vl:",
                    "-l <client_identifier>"},
            {"MqttDisconnect", &MqttBrokerTool::MqttDisconnect, "c:f:vl:",
                    "-l <client_identifier>"},
            {"ProtoHttpPublish", &MqttBrokerTool::ProtoHttpPublish, "i:o:c:f:vx:y:d:q:r:t:p:s:",
                    "-i <ip> -o <port> -x <pub_client_id> -y <sub_client_id> -d <dup> -q <qos> -r <retain> -t <topic_name> -p <packet_identifier> -s <string>"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

